module.exports = function(config) {
	config.set({
		basePath: '../..',
		files: [
			'build/classy.min.js',
			'src/NamespaceManagerTest.js',
			'src/TypeCheckerTest.js',
			'src/Access/TypeTest.js',
			'src/Access/ControllerTest.js',
			'src/Type/ClassTest.js',
			'src/Type/Class/DefinitionTest.js',
			'src/Type/InterfaceTest.js',
			'src/Type/Interface/DefinitionTest.js',
			'src/Type/FactoryTest.js',
			'src/Type/DefinitionFactoryTest.js',
			'src/Member/PropertyTest.js',
			'src/Member/Property/DefinitionTest.js',
			'src/Member/MethodTest.js',
			'src/Member/Method/DefinitionTest.js',
			'src/Member/EventTest.js',
			'src/Member/Event/DefinitionTest.js',
			'src/Member/ConstantTest.js',
			'src/Member/Constant/DefinitionTest.js',
			'src/Member/FactoryTest.js',
			'src/Member/DefinitionFactoryTest.js',
			'src/Registry/TypeTest.js',
			'src/Registry/MemberTest.js',
			'src/AutoLoaderTest.js',
			'src/Reflection/TypeTest.js',
			'tests/integration-tests/TypeDeclaration.js',
			'tests/integration-tests/Instantiation.js',
			'tests/integration-tests/Properties.js',
			'tests/integration-tests/Methods.js',
			'tests/integration-tests/Events.js',
			'tests/integration-tests/Constants.js',
			'tests/integration-tests/Inheritance.js',
			'tests/integration-tests/AccessControl.js',
			'tests/integration-tests/Interfaces.js',
			'tests/integration-tests/Autoloading.js',
			'tests/integration-tests/Reflection.js',
			{
				pattern: 'tests/integration-tests/Autoloading/**/*.js',
				watched: true,
				included: false,
				served: true
			}
		],
		frameworks: ['jasmine'],
		browsers: ['PhantomJS']
	});
};
